version: '3.3'


services:
 db:
  image: mysql:5.7
  container_name: db
  volumes:
    - ./database/:/docker-entrypoint-initdb.d
  restart: always
  environment:
    - MYSQL_DATABASE=content_stealer
    - MYSQL_USER=user
    - MYSQL_PASSWORD=qwerty
    - MYSQL_ROOT_PASSWORD=rootpass,
  ports:
    - "33006:3306"