# Generated by Django 2.2 on 2019-04-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hash',
            new_name='link',
        ),
    ]
