# Generated by Django 2.2 on 2019-04-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190403_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='permalink',
            new_name='hash',
        ),
    ]
